export const firebaseCollections = {
  smsMessages: "smsMessages",
  farmers: "farmers",
  auditLogs: "auditLogs",
  outboundMessages: "outboundMessages",
  resources: "resources",
  marketPrices: "marketPrices",
  alertHistory: "alertHistory",
  assistanceRecords: "assistanceRecords",
  fieldVisitTasks: "fieldVisitTasks",
  knowledgeArticles: "knowledgeArticles",
  vouchers: "vouchers",
  users: "users",
  accessRequests: "accessRequests",
  systemHealth: "systemHealth",
  systemSettings: "systemSettings",
  logbookEntries: "logbookEntries",
  smsTrainingExamples: "smsTrainingExamples",
  mobileDeviceTokens: "mobileDeviceTokens",
} as const;
