import { isDemoMode } from "@/lib/config/app-mode";
import { demoAuditRepository } from "@/lib/repositories/audit/demo-audit-repository";
import { liveAuditRepository } from "@/lib/repositories/audit/live-audit-repository";
import { demoAlertHistoryRepository } from "@/lib/repositories/alert-history/demo-alert-history-repository";
import { liveAlertHistoryRepository } from "@/lib/repositories/alert-history/live-alert-history-repository";
import { demoAssistanceRepository } from "@/lib/repositories/assistance/demo-assistance-repository";
import { liveAssistanceRepository } from "@/lib/repositories/assistance/live-assistance-repository";
import { demoFarmerRepository } from "@/lib/repositories/farmers/demo-farmer-repository";
import { liveFarmerRepository } from "@/lib/repositories/farmers/live-farmer-repository";
import { demoFieldVisitRepository } from "@/lib/repositories/field-visits/demo-field-visit-repository";
import { liveFieldVisitRepository } from "@/lib/repositories/field-visits/live-field-visit-repository";
import { demoKnowledgeRepository } from "@/lib/repositories/knowledge/demo-knowledge-repository";
import { liveKnowledgeRepository } from "@/lib/repositories/knowledge/live-knowledge-repository";
import { demoLogbookRepository } from "@/lib/repositories/logbook/demo-logbook-repository";
import { liveLogbookRepository } from "@/lib/repositories/logbook/live-logbook-repository";
import { demoMarketPriceRepository } from "@/lib/repositories/market-prices/demo-market-price-repository";
import { liveMarketPriceRepository } from "@/lib/repositories/market-prices/live-market-price-repository";
import { demoOutboundRepository } from "@/lib/repositories/outbound/demo-outbound-repository";
import { liveOutboundRepository } from "@/lib/repositories/outbound/live-outbound-repository";
import { demoResourceRepository } from "@/lib/repositories/resources/demo-resource-repository";
import { liveResourceRepository } from "@/lib/repositories/resources/live-resource-repository";
import { demoSmsRepository } from "@/lib/repositories/sms/demo-sms-repository";
import { liveSmsRepository } from "@/lib/repositories/sms/live-sms-repository";
import { demoSmsTrainingRepository } from "@/lib/repositories/sms-training/demo-sms-training-repository";
import { liveSmsTrainingRepository } from "@/lib/repositories/sms-training/live-sms-training-repository";
import { demoSystemSettingsRepository } from "@/lib/repositories/system-settings/demo-system-settings-repository";
import { liveSystemSettingsRepository } from "@/lib/repositories/system-settings/live-system-settings-repository";
import { demoUserRepository } from "@/lib/repositories/users/demo-user-repository";
import { liveUserRepository } from "@/lib/repositories/users/live-user-repository";
import { demoVoucherRepository } from "@/lib/repositories/vouchers/demo-voucher-repository";
import { liveVoucherRepository } from "@/lib/repositories/vouchers/live-voucher-repository";

export const smsRepository = isDemoMode ? demoSmsRepository : liveSmsRepository;
export const smsTrainingRepository = isDemoMode ? demoSmsTrainingRepository : liveSmsTrainingRepository;
export const farmerRepository = isDemoMode ? demoFarmerRepository : liveFarmerRepository;
export const auditRepository = isDemoMode ? demoAuditRepository : liveAuditRepository;
export const alertHistoryRepository = isDemoMode ? demoAlertHistoryRepository : liveAlertHistoryRepository;
export const assistanceRepository = isDemoMode ? demoAssistanceRepository : liveAssistanceRepository;
export const fieldVisitRepository = isDemoMode ? demoFieldVisitRepository : liveFieldVisitRepository;
export const knowledgeRepository = isDemoMode ? demoKnowledgeRepository : liveKnowledgeRepository;
export const logbookRepository = isDemoMode ? demoLogbookRepository : liveLogbookRepository;
export const marketPriceRepository = isDemoMode ? demoMarketPriceRepository : liveMarketPriceRepository;
export const outboundMessageRepository = isDemoMode ? demoOutboundRepository : liveOutboundRepository;
export const resourceRepository = isDemoMode ? demoResourceRepository : liveResourceRepository;
export const voucherRepository = isDemoMode ? demoVoucherRepository : liveVoucherRepository;
export const systemSettingsRepository = isDemoMode ? demoSystemSettingsRepository : liveSystemSettingsRepository;
export const userRepository = isDemoMode ? demoUserRepository : liveUserRepository;
